apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes-app
  labels:
    app: quotes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quotes-app
  template:
    metadata:
      labels:
        app: quotes-app
    spec:
      containers:
      - name: quotes-app
        image: ankuradarsh/quotes:0.0.1  # Replace with your Docker image name
        ports:
        - containerPort: 5000    # Replace with the port your app listens on
